Update scripts to prompt Linux users to action rather than unnecessarily failing

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -1,7 +1,8 @@
 #!/bin/bash
 
 # Configure the temporary directory.
-if [ "$(uname)" != "Darwin" ]; then
+PLATFORM="$(uname)"
+if [ "${PLATFORM}" != "Darwin" ] && [ "${PLATFORM}" != "Linux" ]; then
 	echo "This script is for Mac only."
 	exit 1
 fi
@@ -22,46 +23,77 @@ check() {
 	[ $? -eq 0 ] || fail "Cannot $1."
 }
 
-# Download and install Git, if necessary.
-if ! git --version > /dev/null 2>&1; then
-	DMG="$T/git-2.6.2-intel-universal-mavericks.dmg"
-	curl -o "$DMG" 'https://phoenixnap.dl.sourceforge.net/project/git-osx-installer/git-2.6.2-intel-universal-mavericks.dmg'
-	check "download Git"
-	hdiutil attach "$DMG"
-	check "attach Git DMG file"
-	cd "/Volumes/Git 2.6.2 Mavericks Intel Universal"
-	sudo installer -pkg *.pkg -target /
-	check "install Git"
-	cd $HOME
-	hdiutil detach "/Volumes/Git 2.6.2 Mavericks Intel Universal"
-	rm $DMG
-fi
+install_darwin() {
+	# Download and install Git, if necessary.
+	if ! git --version > /dev/null 2>&1; then
+		DMG="$T/git-2.6.2-intel-universal-mavericks.dmg"
+		curl -o "$DMG" 'https://phoenixnap.dl.sourceforge.net/project/git-osx-installer/git-2.6.2-intel-universal-mavericks.dmg'
+		check "download Git"
+		hdiutil attach "$DMG"
+		check "attach Git DMG file"
+		cd "/Volumes/Git 2.6.2 Mavericks Intel Universal"
+		sudo installer -pkg *.pkg -target /
+		check "install Git"
+		cd $HOME
+		hdiutil detach "/Volumes/Git 2.6.2 Mavericks Intel Universal"
+		rm $DMG
+	fi
 
-# Download and install Node, if necessary.
-if ! node --version > /dev/null 2>&1; then
-	PKG="$T/node-v8.11.3.pkg"
-	curl -o "$PKG" 'https://nodejs.org/dist/v8.11.3/node-v8.11.3.pkg'
-	check "download Node"
-	sudo installer -pkg "$PKG" -target /
-	check "install Node"
-else
-	V=$(node --version | sed -e 's/v//' -e 's/\..*//')
-	if [ $V -lt 6 ]; then
-		echo -e "\033[0;31mYour current version of node is less than 6.  Before re-running this script,"
-		echo "you must either uninstall the current version or, if you already have a later"
-		echo "version installed, ensure it is earlier in your path so this and other"
-		echo -e "Developer Rig scripts will use it.\033[0m"
+	# Download and install Node, if necessary.
+	if ! node --version > /dev/null 2>&1; then
+		PKG="$T/node-v8.11.3.pkg"
+		curl -o "$PKG" 'https://nodejs.org/dist/v8.11.3/node-v8.11.3.pkg'
+		check "download Node"
+		sudo installer -pkg "$PKG" -target /
+		check "install Node"
+	else
+		V=$(node --version | sed -e 's/v//' -e 's/\..*//')
+		if [ $V -lt 6 ]; then
+			echo -e "\033[0;31mYour current version of node is less than 6.  Before re-running this script,"
+			echo "you must either uninstall the current version or, if you already have a later"
+			echo "version installed, ensure it is earlier in your path so this and other"
+			echo -e "Developer Rig scripts will use it.\033[0m"
+			exit 1
+		fi
+	fi
+
+	# Download and install Yarn, if necessary.
+	if ! yarn --version > /dev/null 2>&1; then
+		touch ~/.profile
+		rm -rf ~/.yarn
+		curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --rc
+		check "install Yarn"
+		echo -e "\033[1;32mNOTE:\033[0;32m  A fresh installation of Yarn requires a new terminal window.  Please run"
+		echo -e "the script again in a new terminal window\033[0m."
 		exit 1
 	fi
-fi
+}
 
-# Download and install Yarn, if necessary.
-if ! yarn --version > /dev/null 2>&1; then
-	touch ~/.profile
-	rm -rf ~/.yarn
-	curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --rc
-	check "install Yarn"
-	echo -e "\033[1;32mNOTE:\033[0;32m  A fresh installation of Yarn requires a new terminal window.  Please run"
-	echo -e "the script again in a new terminal window\033[0m."
-	exit 1
-fi
+install_linux() {
+	# Check for git
+	local MISSING=()
+	if ! git --version > /dev/null 2>&1; then
+		MISSING+=("git")
+	fi
+
+	# Check for node
+	if ! node --version > /dev/null 2>&1; then
+		MISSING+=("nodejs")
+	fi
+
+	# Check for yarn
+	if ! yarn --version > /dev/null 2>&1; then
+		MISSING+=("yarn")
+	fi
+
+	if [ ${#MISSING[@]} -gt 0 ]; then
+		echo -e "\033[1;32mNOTE:\033[0;32m  The following commands where not found: ${MISSING[@]}"
+		echo -e "\033[1;32mNOTE:\033[0;32m  Please install the necessary packages and try again."
+		exit 1
+	fi
+}
+
+case "${PLATFORM}" in
+	"Linux") install_linux ;;
+	"Darwin") install_darwin ;;
+esac
diff --git a/scripts/make-cert b/scripts/make-cert
--- a/scripts/make-cert
+++ b/scripts/make-cert
@@ -4,9 +4,11 @@
 # https://stackoverflow.com/questions/21297139/how-do-you-sign-a-certificate-signing-request-with-your-certification-authority
 # https://stackoverflow.com/questions/35031149/set-imported-certificate-to-always-be-trusted-in-mac-os-x
 
+PLATFORM="$(uname)"
+
 # Check the platform.
-if [ "$(uname)" != "Darwin" ]; then
-	echo "This script is for Mac only."
+if [ "${PLATFORM}" != "Darwin" ] && [ "${PLATFORM}" != "Linux" ]; then
+	echo "This script is for Mac & Linux only."
 	exit 1
 fi
 
@@ -35,8 +37,15 @@ check() {
 NEEDS_INSTALLATION=true
 SSL="$D/../ssl"
 if [ -s "$SSL/cacert.crt" -a -s "$SSL/cacert.key" -a -s "$SSL/selfsigned.crt" -a -s "$SSL/selfsigned.key" -a -s "$SSL/server.crt" -a -s "$SSL/server.key" ]; then
-	# The certificates have been previously created.  Determine if the certificates need installation.
-	security find-certificate -a | grep -Fq "Twitch Developer Rig CA" && NEEDS_INSTALLATION=false
+	case $PLATFORM in
+		"Darwin")
+			# The certificates have been previously created.  Determine if the certificates need installation.
+			security find-certificate -a | grep -Fq "Twitch Developer Rig CA" && NEEDS_INSTALLATION=false
+			;;
+		"Linux")
+			trust list | grep -Fq "Twitch Developer Rig CA" && NEEDS_INSTALLATION=false
+			;;
+	esac
 else
 	# Determine the availability of OpenSSL.
 	openssl version > /dev/null 2>&1
@@ -90,8 +99,7 @@ mkdir -p "$CONF"
 cp "$SSL"/server.* "$CONF"
 check "place the extension server certificate files"
 
-# Add all certificates to the local machine's root certificate store.
-if $NEEDS_INSTALLATION; then
+install_cert_darwin() {
 	touch /etc/hosts 2> /dev/null || echo "Please enter your password to install the Twitch Developer Rig certificate."
 	sudo security add-trusted-cert -d -p ssl -u -1 -k /Library/Keychains/System.keychain "$SSL/cacert.crt"
 	check "add the CA certificate to the local machine's root certificate store"
@@ -148,4 +156,39 @@ if $NEEDS_INSTALLATION; then
 		echo -e 'Press "return" to acknowledge.\033[0m'
 		read L
 	fi
+}
+
+install_cert_linux() {
+	if [ -d "/usr/local/share/ca-certificates" ]; then
+		local dest="/usr/local/share/ca-certificates/twitch-developer-rig"
+		touch /etc/hosts 2> /dev/null || echo "Please enter your password to install the Twitch Developer Rig certificate."
+
+		if [ ! -d "${dest}" ]; then
+			sudo mkdir -p "${dest}"
+		fi
+
+		for name in server selfsigned; do
+			echo "$name.crt"
+			sudo cp "${name}.crt" "${dest}/{$name}.crt"
+			check "add the $name certificate to the local machine's root certificate store"
+		done
+		sudo update-ca-certificates
+	else
+		echo -e '\033[1;35mNOTE:\033[0;35m  Unable to determine certificate destination on your machine.'
+		echo -e '\033[1;35mNOTE:\033[0;35m  Please manually install ssl/server.crt and ssl/selfsigned.crt to the global trust.'
+	fi
+
+	echo -e '\033[1;35mNOTE:\033[0;35m  If you are using Firefox, you may have to manually add certs to avoid trust errors.'
+}
+
+# Add all certificates to the local machine's root certificate store.
+if $NEEDS_INSTALLATION; then
+	case "${PLATFORM}" in
+		"Darwin")
+			install_cert_darwin
+			;;
+		"Linux")
+			install_cert_linux
+			;;
+	esac
 fi
